# Generated by Django 2.0.1 on 2018-02-12 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('date', models.DateField(default=datetime.date.today)),
                ('organizors', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EventWinners',
            fields=[
                ('event_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('first_winner', models.CharField(max_length=25)),
                ('second_winner', models.CharField(max_length=25)),
                ('third_winner', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=25)),
                ('student_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=10)),
                ('mail_id', models.CharField(max_length=30)),
            ],
        ),
    ]
